apiVersion: v1
kind: Service
metadata:
  name: gdg-demo-service
spec:
  selector:
    app: gdg-microservices
  ports:
    - protocol: "TCP"
      # Port accessible inside the cluster
      port: 8080
      # Port that needs to routed inside the pod (respective containers port)
      targetPort: 8080
      # Port that service listen on the given node
      nodePort: 30001
  type: LoadBalancer