apiVersion: v1
kind: Service
metadata:
  name: gdg-demo-service
spec:
  selector:
    app: gdg-microservices
  ports:
    - protocol: "TCP"
      # Port that will be exposed at the cluster level,
      #eventually the port that will be exposed to outside
      port: 8080
      # Port that listens at the container level
      targetPort: 8080
      # Port that will be exposed at the node level
      nodePort: 30001
  type: LoadBalancer